export enum HTTP_STATUS_CODE {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export enum ENUM_JOB_TITLE {
  EXECUTIVE_PRODUCER = 'EXECUTIVE_PRODUCER',
  PRODUCER = 'PRODUCER',
  ASSOCIATE_PRODUCER = 'ASSOCIATE_PRODUCER',
  LINE_PRODUCER = 'LINE_PRODUCER',
  PRODUCTION_MANAGER = 'PRODUCTION_MANAGER',
  PRODUCTION_CONTROLLER = 'PRODUCTION_CONTROLLER',
  PRODUCTION_COORDINATOR = 'PRODUCTION_COORDINATOR',
  ACCOUNT_EXECUTIVE = 'ACCOUNT_EXECUTIVE',
}

export enum ENUM_VIDEO_PRODUCTION_ROLE {
  EXECUTIVE_AND_MANAGEMENT = 'EXECUTIVE_AND_MANAGEMENT',
  CREATIVE_AND_DIRECTION = 'CREATIVE_AND_DIRECTION',
  ART_AND_SET_DESIGN = 'ART_AND_SET_DESIGN',
  CINEMATOGRAPHY_AND_CAMERA = 'CINEMATOGRAPHY_AND_CAMERA',
  LIGHTING_AND_ELECTRICAL = 'LIGHTING_AND_ELECTRICAL',
  SOUND_AND_MUSIC = 'SOUND_AND_MUSIC',
  VISUAL_EFFECTS_AND_ANIMATION = 'VISUAL_EFFECTS_AND_ANIMATION',
  EDITING_AND_POST_PRODUCTION = 'EDITING_AND_POST_PRODUCTION',
}

export enum ENUM_PRESIGNED_UPLOAD_TYPE {
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  COVER_PICTURE = 'COVER_PICTURE',
}

export enum ENUM_PRESIGNED_UPLOAD_KEY {
  PROFILE_PICTURE = 'objectId',
}

export enum ENUM_MAX_FILE_SIZE_MB {
  NEED_SUPPORT_ATTACHMENT = 10,
}

export enum ENUM_FILE_TYPE {
  IMAGE = 'image/png,image/jpg',
  VIDEO = '.mp4,.mov',
  EXCEL = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ZIP = 'zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed',
}

export enum ENUM_ADD_WORK_TYPE {
  COMMERCIAL_VIDEO = 'COMMERCIAL_VIDEO',
  KEY_VISUAL_IMAGE = 'KEY_VISUAL_IMAGE',
}

export enum ENUM_DATE_FORMAT {
  DATE = 'yyyy/MM/dd',
  MONTH = 'yyyy/MM',
  HOUR = 'yyyy/MM/dd HH:mm',
  TIME = 'yyyy/MM/dd HH:mm:ss',
  LONG = 'MMMM dd, yyyy',
  INPUT = 'yyyy-MM-dd',
}

export enum ENUM_EXTERNAL_LINK {
  CONTENT_CREDENTIAL = 'https://contentcredentials.org/',
}
